# Generated by Django 4.2.5 on 2024-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_img', models.ImageField(upload_to='sliderimg/')),
                ('cms_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('cms_age', models.CharField(max_length=20, verbose_name='Возраст')),
                ('cms_description', models.CharField(max_length=20, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайд',
            },
        ),
    ]
