# Generated by Django 4.2.5 on 2024-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_form_dt', models.DateTimeField(auto_now=True)),
                ('order_name_surname', models.CharField(max_length=200)),
                ('order_age', models.CharField(max_length=100)),
                ('order_location', models.CharField(max_length=200)),
                ('order_circumstances', models.CharField(max_length=200)),
                ('order_additional_info', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
